config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  
  resource :dashboard, controller: :dashboard, only: [:show]

  root 'static_pages#home'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def show
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    if user_signed_in?
      redirect_to dashboard_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/_footer.slim
h1 Footer

app/views/dashboard/_topbar.slim
div.sticky
  nav.top-bar data-topbar="" role="navigation" 
    ul.title-area
      li.name
        h1
          a href="#"
            = APP_NAME
      li.toggle-topbar.menu-icon
        a href="#" 
          span Menu
    section.top-bar-section
      /! Right Nav Section
      ul.right
        li.active
          = link_to current_user.username, '#'
        li
          = link_to 'Sign out', destroy_user_session_path, method: :delete

app/views/dashboard/show.slim
h1 Dashboard

p 
  = "Hello, #{ current_user.username }! You are now signed in as {current_user.role}"

app/views/layouts/application.slim
doctype html
html lang="en" 
  head
    meta charset="utf-8" /
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    title= content_for?(:title) ? yield(:title) : 'OnEx'
    = stylesheet_link_tag 'application'
    style
      = yield :stylesheets
    = javascript_include_tag 'vendor/modernizr'
    = csrf_meta_tags
  body
    = yield :topbar
    div#main
      = yield
    footer
      = yield :footer
    script
      = yield :javascripts
    = javascript_include_tag 'application'

app/views/layouts/dashboard.slim
- content_for :topbar do
  = render 'dashboard/topbar'

- content_for :footer do
  = render 'dashboard/footer'
  
= render template: 'layouts/application'

app/views/layouts/static_pages.slim
- content_for :topbar do
  = render 'static_pages/topbar'

- content_for :footer do
  = render 'static_pages/footer'
  
= render template: 'layouts/application'

app/views/shared/_notification.slim
- if notice
  p.alert.alert-success
    = notice

- if alert
  p.alert.alert-danger
    = alert

app/views/static_pages/_footer.slim
h1 Sitemap

app/views/static_pages/_topbar.slim
div.sticky
  nav.top-bar data-topbar="" role="navigation" 
    ul.title-area
      li.name
        h1
          a href="#"
            = APP_NAME
      li.toggle-topbar.menu-icon
        a href="#" 
          span Menu
    section.top-bar-section
      /! Right Nav Section
      ul.right
        li.active
          = link_to 'Sign in', new_user_session_path
        li
          = link_to 'Sign up', new_user_registration_path

app/views/static_pages/home.slim
h1 OnEx
p
  | Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

app/views/users/shared/_links.slim
- if controller_name != 'sessions'
  = link_to "Sign in", new_session_path(resource_name)
  br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    br/